### ISSUE TITLE
[FE] 메인페이지 수정 요청

### ISSUE THREAD

**Issue by ddolboghi** [4-ComehereTeam/ssg-client#14]
메인페이지에 접속하면 다음과 같은 경고가 터미널에 나타나네요. 유니버스 클럽 이미지 때문인것 같습니다.
유니버스 클럽 이미지만 따로 관리하는게 어떨까요?
```
 ⚠ The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead.
 ✓ Compiled in 497ms (304 modules)
 ⚠ The requested resource "https://sui.ssgcdn.com/cmpt/banner/202401/2024010509151151913264546326_754.webp" is an animated image so it will not be optimized. Consider adding the "unoptimized" property to the <Image>.
 ✓ Compiled /favicon.ico in 158ms (364 modules)
```
---

하단 네비게이션바가 푸터보다 뒤에 있네요. z-index 조정이 필요해보입니다
![image](https://github.com/ComehereTeam/ssg-client/assets/100576111/0670a605-5800-4b48-b273-281ff9b14be9)

### 관련된 브랜치
#7

**Comment by sw-devr** [comment]
경고 해결했습니다 ! 
기존의 `<img>` 태그 대신에 `<Image>` 태그로 수정하니 경고가 안뜨네요
피드백 감사합니다 !

**Comment by ddolboghi** [comment]
감사합니다!
