### ISSUE TITLE
fix request: 메인페이지 좌측 상단 로고가 안뜹니다.

### ISSUE THREAD

**Issue by ddolboghi** [4-ComehereTeam/ssg-client#32]
## 어떤 에러인가요?

최신 dev 브랜치를 pull 받았는데, 메인페이지의 좌측 상단 로고를 불러오지 못하고 있습니다.
![image](https://github.com/ComehereTeam/ssg-client/assets/100576111/da2dba78-86e6-4a35-bad0-ce25a944fccf)

그리고 브라우저 콘솔창에 다음과 같은 에러 로그가 나타납니다.
```
GET http://localhost:3000/_next/image?url=https%3A%2F%2Fsui.ssgcdn.com%2Fui%2Fmssgmall-ssg%2Fimages%2Fbadge%2Fmall%2Flogo%2Fssg.svg%3Fq%3Dd0e074aad3aee3ba776c3af1f3848117a67005b4&w=256&q=75 400 (Bad Request)
```
수정해서 PR 올려주시면 감사하겠습니다~

## 관련된 브랜치
#31

**Comment by sw-devr** [comment]
메인페이지의 로고이미지는 `<img>` 태그로 감싸야 하더라고요 
왜 그런지 이유는 저도 궁금해서 검색해봤지만 정확한 이유는 찾지못했지만 해결책은 찾았습니다
`<Image>` 태그의 loader 기능을 활용하면 해결이 된다고 합니다.
 
![image](https://github.com/ComehereTeam/ssg-client/assets/141290308/714b7266-4559-4434-8fac-74410f7f180a)

출처 : https://velog.io/@gbwlxhd97/NEXT-JS-IMAGE-%ED%83%9C%EA%B7%B8-400-error-%ED%95%B4%EA%B2%B0%EB%B0%A9%EB%B2%95

**Comment by ddolboghi** [comment]
공식문서 보니까 loader가 url에서 이미지 불러올때 사용하는 거였네요
그래서 이렇게 고쳤더니 
```tsx
"use client"

import Image from "next/image"

export default function HeaderWithSearchBar() {
  const imageLoader = () => {
    return "https://sui.ssgcdn.com/ui/mssgmall-ssg/images/badge/mall/logo/ssg.svg?q=d0e074aad3aee3ba776c3af1f3848117a67005b4"
  }

  return (
    <>
      <header className="flex flex-row justify-between items-center py-[8px] px-[10px] h-[56px] w-full">
        <div className="flex flex-shrink-0">
          <a href="/">
            <Image
              loader={imageLoader}
              alt="SSG.COM"
              src="logo.png"
              width={86}
              height={40}
            />
          </a>
          ...
```
잘 나오네요!
![image](https://github.com/ComehereTeam/ssg-client/assets/100576111/6021d880-fc5b-424a-83f1-27fd12cc9667)


감사합니다~!

**Comment by sw-devr** [comment]
👍👍 다행이네요
