### ISSUE TITLE
fix request : 로그인 시 나온 에러 수정해주세요

### ISSUE THREAD

**Issue by sw-devr** [4-ComehereTeam/ssg-client#37]
## 어떤 기능인가요?

> 로그인시 해당 에러메시지가 뜹니다 
> next-auth/next 가 없어졌다는 내용인 것 같은데 확인부탁드리겠습니다 !

## 참고할만한 자료(선택)
![image](https://github.com/ComehereTeam/ssg-client/assets/141290308/b7317db5-7a0e-4e97-954c-9b727673575f)

**Comment by ddolboghi** [comment]
지금 승원님 로컬에 next-auth 5버전이 설치되있어서 next-auth/next가 사용되지 않는다는 에러 로그입니다.

yarn install 실행해서 최신 pakage.json을 설치하시면 해결됩니다~

**Comment by sw-devr** [comment]
감사합니다 해결되었습니다 👍👍
